# DevTools
spring.devtools.livereload.enabled=true

# Oracle
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
#spring.datasource.username=YOUR_USERNAME
#spring.datasource.password=YOUR_PASSWORD

# DB 연결 없이 실행 (Oracle 미설치 환경)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# logger level 
logging.level.com.example.test=DEBUG
logging.level.org.mybatis=DEBUG

# JWT
jwt.secret=bG9jYWwtc2VjcmV0LWtleS1mb3ItbG9jYWwtZW52aXJvbm1lbnQtb25seQ==
