spring.application.name=Test

# MyBatis (환경 무관)
mybatis.mapper-locations=classpath:mappers/**/*.xml
mybatis.type-aliases-package=com.example.test
mybatis.configuration.map-underscore-to-camel-case=true

# JWT 만료 시간 (공통)
jwt.expiration=86400000
