# Oracle (�)
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@//YOUR_DEV_HOST:1521/YOUR_SERVICE_NAME
#spring.datasource.username=YOUR_USERNAME
#spring.datasource.password=YOUR_PASSWORD

# logger (INFO 수준)
logging.level.com.example.test=INFO

# JWT (secret key - dev)
jwt.secret=ZGV2LXNlY3JldC1rZXktZm9yLWRldi1lbnZpcm9ubWVudC1vbmx5
